STOCK_API_KEY = "PUT_YOUR_ALPHA_VANTAGE_KEY"
NEWS_API_KEY = "PUT_YOUR_NEWSAPI_KEY"
sms_account_sid = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
auth_token = "PUT_YOUR_TWILIO_AUTH_TOKEN"
from_ = "+10000000000"
to = "+10000000000"
